In [1]:
from modules import *
import pickle

In [2]:
sql_config = read_config('config/sql_config.json')

In [3]:
news_data=load_from_sql(sql_config,'[dbo].[SS_News]')

D:\實習\專案\mycode\News-keyword-extraction\news_env\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [4]:
news_data = load_data("data/SS_News.csv")

In [5]:
news_data

,newsID,date,source,mkID,mk,title,content,updateTime,display
0,639309354,2022-05-24 13:39:10.000,10jqka_US,US,US,「粵貿全國」線上專區啟動 廣東超1萬粵企參與天貓618,<p> 5月日，廣東省商務廳與淘寶天貓聯合啟動「粵貿全國，魅力廣東」線上專區。5月日到6月...,2022-05-24 16:20:11.530,1.0
1,639309552,2022-05-24 13:55:38.000,10jqka_US,US,US,奧瑞金種業(SEED.US)獲920萬美元供應協議,<p> 5月日，奧瑞金種業(SD.US)宣布，該公司與雲南省飼料公司(Yunnan Fee...,2022-05-24 16:40:03.663,1.0
2,639309910,2022-05-24 14:17:47.000,10jqka_US,US,US,愛彼迎關閉中國境內游業務後，途家開通綠色審核通道助房東過渡,<p> 新京報貝殼財經訊（記者王真真）5月4日，Airbnb（愛彼迎）宣布將於7月日起關閉...,2022-05-24 16:50:02.443,1.0
3,639309930,2022-05-24 14:19:15.000,10jqka_US,US,US,暫停中國境內房源預訂 愛彼迎業務大調整,<p> 全球最大的民宿平台Airbnb（愛彼迎）做出重大業務調整。5月4日，愛彼迎中國宣布...,2022-05-24 16:50:02.443,1.0
4,639309973,2022-05-24 14:22:14.000,10jqka_US,US,US,上任僅一個多月 巴西石油公司(PBR.US)CEO遭解僱,<p> 巴西總統博索納羅周一解僱了巴西石油公司(PBR.US)執行長Jose Mauro ...,2022-05-24 16:50:02.443,1.0
...,...,...,...,...,...,...,...,...,...
52782,SQ20220519080017113,2022-05-19 08:00:17.000,SQ,54,財訊新聞,亞東晨盤：,待續,2022-05-19 08:00:25.493,1.0
52783,SQ20220519080024114,2022-05-19 08:00:24.000,SQ,54,財訊新聞,電子時報：MacBook遷移至重慶生產？蘋果、ODM將創雙贏,【財訊快報／編輯部】華東大封城導致外商逃離的消息甚囂塵上，此次封城主要受災戶之一的蘋果(Ap...,2022-05-19 08:00:46.303,1.0
52784,SQ20220519080026115,2022-05-19 08:00:26.000,SQ,54,財訊新聞,電子時報：特規品MOSFET需求昂揚，標準品4Q庫存壓力恐炸鍋,【財訊快報／編輯部】基礎功率元件金氧半場效電晶體(MOSFET)近期因商用、電競NB等需求仍...,2022-05-19 08:00:46.400,1.0
52785,SQ20220519080030116,2022-05-19 08:00:30.000,SQ,54,財訊新聞,財訊快報：裕融樂觀今年全年業績成長二至三成，大陸市場盼維持去年水準,【財訊快報／記者戴海茜報導】裕融(9941)昨天舉行集團線上法說會，副總林群盛指出，大陸封控...,2022-05-19 08:00:46.493,1.0
52786,SQ20220519080032117,2022-05-19 08:00:32.000,SQ,54,財訊新聞,經濟日報頭條：面板雙虎，市場傳合併,【財訊快報／編輯部】鴻海集團將撤出群創(3481)董事會，友達集團前董事長李焜耀不再參選董事...,NaN,NaN

In [6]:
news_data=news_data[:3]

In [7]:
model_config = read_config('config/model_config.json')

In [8]:
news_data,ws,pos=ws(news_data,"data/news_nlp.data",model_config)

D:\實習\專案\mycode\News-keyword-extraction\python\modules\word_split.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news_data['title'] = news_data['title'].apply(lambda x : x.replace(" ", "").replace("\t", "").replace("　", ""))
D:\實習\專案\mycode\News-keyword-extraction\python\modules\word_split.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news_data['content'] = news_data['content'].apply(lambda x : x.replace(" ", "").replace("\t", "").replace("　", ""))
Tokenization: 100%|██████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 242.37it/s]
Inference: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:20<00:00, 20.65s/it]
Tokenization: 100%|█████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3037.15it/s]
Inference: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.58it/s]
Tokenization: 100%|█████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1505.31it/s]
Inference: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.64it/s]

In [9]:
config = read_config('config/extract_config.json')

In [10]:
stopwords = read_config('config/pos_arg.json')

In [11]:
keyword_dfl=ke3(news_data,ws,pos,config,stopwords)

start analysis:
tfidf...done
textrank...done
keyword_score...start

Some weights of BertModel were not initialized from the model checkpoint at model/bert-base-chinese and are newly initialized: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Token indices sequence length is longer than the specified maximum sequence length for this model (811 > 512). Running this sequence through the model will result in indexing errors

keyword_score...done

In [12]:
# kdfl_2_sql(keyword_dfl,'keyword_data',sql_config)

In [13]:
with open("./data/news_keyword_dfl.p", "rb") as fp:
    keyword_dfl = pickle.load(fp)

In [14]:
for i in keyword_dfl[:10]:
    display(i)

,newsID,word,pos,in_title,keybert_score,tfidf_score,textrank_score,keybert_rank,tfidf_rank,textrank_rank,total_rank
0,639309354,天貓,Nb,0.434783,0.6615,0.308141,0.020365,0.215821,0.515182,0.495325,23
1,639309354,國,Nc,0.434783,0.6628,0.237031,0.009428,0.216246,0.396293,0.229298,22
2,639309354,粵貿,Nc,0.434783,0.6519,0.189625,0.009350,0.212689,0.317035,0.227398,21
3,639309354,淘寶,Nb,0.000000,0.6309,0.308141,0.017841,0.205838,0.515182,0.433935,20
4,639309354,專區,Nc,0.434783,0.6357,0.142219,0.007889,0.207404,0.237776,0.191873,19
5,639309354,商家,Na,0.000000,0.6301,0.142219,0.014208,0.205577,0.237776,0.345570,18
6,639309354,粵,Nc,0.434783,0.6413,0.023703,0.003613,0.209231,0.039629,0.087878,17
7,639309354,平台,Na,0.000000,0.6356,0.108161,0.012010,0.207371,0.180835,0.292118,16
8,639309354,品牌,Na,0.000000,0.6548,0.071109,0.007650,0.213635,0.118888,0.186074,15
9,639309354,產業,Na,0.000000,0.6364,0.071109,0.007673,0.207632,0.118888,0.186621,14
10,639309354,日,Na,0.000000,0.6238,0.041998,0.007669,0.203521,0.070217,0.186535,13
11,639309354,產業帶,Na,0.000000,0.6437,0.047406,0.005831,0.210014,0.079259,0.141812,12
12,639309354,APP,Na,0.000000,0.6308,0.047406,0.005499,0.205805,0.079259,0.133751,11
13,639309354,國內,Nc,0.000000,0.6691,0.036054,0.004437,0.218301,0.060278,0.107922,10
14,639309354,市場,Nc,0.000000,0.6384,0.036054,0.004647,0.208285,0.060278,0.113035,9
15,639309354,成交,VA,0.000000,0.6235,0.023703,0.003722,0.203424,0.039629,0.090529,8
16,639309354,產品,Na,0.000000,0.6535,0.023703,0.003215,0.213211,0.039629,0.078204,7
17,639309354,產業鏈,Na,0.000000,0.6246,0.023703,0.003351,0.203782,0.039629,0.081498,6
18,639309354,電商,Na,0.000000,0.6352,0.023703,0.002994,0.207241,0.039629,0.072811,5
19,639309354,中國,Nc,0.000000,0.6233,0.018027,0.003503,0.203358,0.030139,0.085197,4
20,639309354,大促,Na,0.000000,0.6309,0.023703,0.002886,0.205838,0.039629,0.070182,3
21,639309354,地區,Nc,0.000000,0.628,0.018027,0.002939,0.204892,0.030139,0.071474,2
22,639309354,成果,Na,0.000000,0.6304,0.023703,0.002080,0.205675,0.039629,0.050585,1

,newsID,word,pos,in_title,keybert_score,tfidf_score,textrank_score,keybert_rank,tfidf_rank,textrank_rank,total_rank
0,639309552,種業,Na,0.625,0.6001,0.237538,0.022313,0.245216,0.463898,0.401037,16
1,639309552,奧瑞金,Nb,0.625,0.6131,0.237538,0.018567,0.250529,0.463898,0.333714,15
2,639309552,協議,Na,0.625,0.6659,0.237538,0.015466,0.272104,0.463898,0.277969,14
3,639309552,公司,Nc,0.000,0.6546,0.178153,0.023891,0.267487,0.347924,0.429394,13
4,639309552,總價值,Na,0.000,0.6166,0.118769,0.014316,0.251959,0.231949,0.257297,12
5,639309552,人民幣,Na,0.000,0.612,0.118769,0.010559,0.250079,0.231949,0.189777,11
6,639309552,產量,Na,0.000,0.6071,0.059384,0.012207,0.248077,0.115975,0.219397,10
7,639309552,運營,VA,0.000,0.5925,0.059384,0.011997,0.242111,0.115975,0.215630,9
8,639309552,玉米,Na,0.000,0.6062,0.059384,0.011026,0.247709,0.115975,0.198181,8
9,639309552,訂單,Na,0.000,0.6068,0.059384,0.010843,0.247954,0.115975,0.194890,7
10,639309552,營養,Na,0.000,0.6188,0.059384,0.010283,0.252858,0.115975,0.184817,6
11,639309552,後者,Nh,0.000,0.6083,0.059384,0.010455,0.248567,0.115975,0.187909,5
12,639309552,飼料,Na,0.000,0.5939,0.059384,0.010533,0.242683,0.115975,0.189319,4
13,639309552,發稿,VA,0.000,0.5883,0.059384,0.010419,0.240395,0.115975,0.187259,3
14,639309552,日,Na,0.000,0.5975,0.035073,0.011322,0.244154,0.068496,0.203487,2
15,639309552,需求,Na,0.000,0.6018,0.059384,0.005639,0.245911,0.115975,0.101345,1

,newsID,word,pos,in_title,keybert_score,tfidf_score,textrank_score,keybert_rank,tfidf_rank,textrank_rank,total_rank
0,639309910,愛彼迎,Nb,0.625,0.6394,0.393920,0.030347,0.252438,0.557336,0.542427,16
1,639309910,房東,Na,0.625,0.6361,0.320060,0.023579,0.251135,0.452835,0.421465,15
2,639309910,中國,Nc,0.625,0.6652,0.224690,0.013053,0.262624,0.317901,0.233315,14
3,639309910,民宿,Nc,0.000,0.67,0.344680,0.026566,0.264519,0.487669,0.474843,13
4,639309910,業務,Na,0.625,0.6297,0.074897,0.008978,0.248608,0.105967,0.160472,12
5,639309910,通道,Na,0.625,0.6035,0.049240,0.006054,0.238264,0.069667,0.108203,11
6,639309910,房源,Na,0.000,0.6594,0.172340,0.011113,0.260334,0.243834,0.198634,10
7,639309910,平台,Na,0.000,0.6337,0.112345,0.016073,0.250187,0.158951,0.287296,9
8,639309910,上線,VA,0.000,0.6474,0.073860,0.008585,0.255596,0.104500,0.153442,8
9,639309910,美團,Nb,0.000,0.6161,0.073860,0.006468,0.243239,0.104500,0.115610,7
10,639309910,市場,Nc,0.000,0.6204,0.056172,0.007145,0.244937,0.079475,0.127719,6
11,639309910,新京報,Nb,0.000,0.6017,0.049240,0.006190,0.237554,0.069667,0.110637,5
12,639309910,Airbnb,FW,0.000,0.6433,0.049240,0.004803,0.253978,0.069667,0.085851,4
13,639309910,小豬,Nb,0.000,0.6164,0.049240,0.004560,0.243357,0.069667,0.081500,3
14,639309910,國內,Nc,0.000,0.6418,0.018724,0.003661,0.253385,0.026492,0.065433,2
15,639309910,社區,Nc,0.000,0.6019,0.024620,0.003963,0.237633,0.034833,0.070840,1